/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from "react";
import { useFrame } from "@react-three/fiber";

import { useGLTF } from "@react-three/drei";

export default function Model(props) {
  const group = useRef();
  const { nodes, materials } = useGLTF("/Poimandres.gltf");
  useFrame(() => {
    group.current.rotation.y += 0.004;
  });

  return (
    <group ref={group} {...props} dispose={null} scale={0.4}>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Curve007_1.geometry}
        material={materials["Material.001"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Curve007_2.geometry}
        material={materials["Material.002"]}
      />
    </group>
  );
}
// export default function Model(props) {
//   const group = useRef();
//   const { nodes, materials } = useGLTF("/Ship.gltf");
//   return (
//     <group ref={group} {...props} dispose={null} scale={0.4}>
//       <mesh
//         castShadow
//         receiveShadow
//         geometry={nodes.Cube.geometry}
//         material={materials["LowPolyColours"]}
//       />
//       <mesh
//         castShadow
//         receiveShadow
//         geometry={nodes.Cube.geometry}
//         material={materials["LowPolyGlow"]}
//       />
//     </group>
//   );
// }

useGLTF.preload("/Ship.gltf");
